-- Database for Smart Bus Portal
CREATE DATABASE IF NOT EXISTS bus_portal;
USE bus_portal;

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL, -- Used as Full Name
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    age INT,
    mobile VARCHAR(15),
    city VARCHAR(50), -- Used as District
    gender VARCHAR(20),
    role ENUM('USER', 'ADMIN') DEFAULT 'USER',
    profile_image VARCHAR(255) DEFAULT NULL,
    recovery_code VARCHAR(24),
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Wallet Table (Subscriptions)
CREATE TABLE IF NOT EXISTS wallet (
    user_id INT PRIMARY KEY,
    balance DECIMAL(10, 2) DEFAULT 0.00,
    plan_start_date DATETIME DEFAULT NULL,
    expiry_date DATETIME DEFAULT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3. Bus Passes Table (Journey History)
CREATE TABLE IF NOT EXISTS passes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    pass_code VARCHAR(20) NOT NULL,
    start_point VARCHAR(100),
    end_point VARCHAR(100),
    price DECIMAL(10, 2) DEFAULT 0.00,
    valid_from TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    valid_until TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status ENUM('ACTIVE', 'EXPIRED', 'CANCELLED') DEFAULT 'ACTIVE',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 4. Bus Codes (Scanning Identification)
CREATE TABLE IF NOT EXISTS bus_codes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(20) UNIQUE NOT NULL,
    city VARCHAR(50) NOT NULL, -- District
    start_point VARCHAR(100),
    end_point VARCHAR(100),
    stops TEXT DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Bus Stops Table
CREATE TABLE IF NOT EXISTS bus_stops (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    message TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Transactions Table (Payment Audit Log)
CREATE TABLE IF NOT EXISTS transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    razorpay_payment_id VARCHAR(100),
    razorpay_order_id VARCHAR(100),
    razorpay_signature VARCHAR(255),
    amount DECIMAL(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- DEFAULT DATA
-- Add sample admin (password: admin123)
INSERT IGNORE INTO users (username, email, password, role) 
VALUES ('Admin', 'admin@busportal.com', '$2y$10$NgNSqhxV5wLAukDKbNHtd.jauLPhFJjcCtw1S0PfpXjLHgAHjsOj', 'ADMIN');

-- Sample Bus Codes for testing (10 per district for 38 districts)
INSERT IGNORE INTO bus_codes (code, city, start_point, end_point) VALUES 
('ARI101', 'Ariyalur', 'Ariyalur Central', 'Ariyalur Suburb 1'),
('ARI102', 'Ariyalur', 'Ariyalur Central', 'Ariyalur Suburb 2'),
('ARI103', 'Ariyalur', 'Ariyalur Central', 'Ariyalur Suburb 3'),
('ARI104', 'Ariyalur', 'Ariyalur Central', 'Ariyalur Suburb 4'),
('ARI105', 'Ariyalur', 'Ariyalur Central', 'Ariyalur Suburb 5'),
('ARI106', 'Ariyalur', 'Ariyalur Central', 'Ariyalur Suburb 6'),
('ARI107', 'Ariyalur', 'Ariyalur Central', 'Ariyalur Suburb 7'),
('ARI108', 'Ariyalur', 'Ariyalur Central', 'Ariyalur Suburb 8'),
('ARI109', 'Ariyalur', 'Ariyalur Central', 'Ariyalur Suburb 9'),
('ARI110', 'Ariyalur', 'Ariyalur Central', 'Ariyalur Suburb 10'),
('CPT101', 'Chengalpattu', 'Chengalpattu Central', 'Chengalpattu Suburb 1'),
('CPT102', 'Chengalpattu', 'Chengalpattu Central', 'Chengalpattu Suburb 2'),
('CPT103', 'Chengalpattu', 'Chengalpattu Central', 'Chengalpattu Suburb 3'),
('CPT104', 'Chengalpattu', 'Chengalpattu Central', 'Chengalpattu Suburb 4'),
('CPT105', 'Chengalpattu', 'Chengalpattu Central', 'Chengalpattu Suburb 5'),
('CPT106', 'Chengalpattu', 'Chengalpattu Central', 'Chengalpattu Suburb 6'),
('CPT107', 'Chengalpattu', 'Chengalpattu Central', 'Chengalpattu Suburb 7'),
('CPT108', 'Chengalpattu', 'Chengalpattu Central', 'Chengalpattu Suburb 8'),
('CPT109', 'Chengalpattu', 'Chengalpattu Central', 'Chengalpattu Suburb 9'),
('CPT110', 'Chengalpattu', 'Chengalpattu Central', 'Chengalpattu Suburb 10'),
('CHN101', 'Chennai', 'Chennai Central', 'Chennai Suburb 1'),
('CHN102', 'Chennai', 'Chennai Central', 'Chennai Suburb 2'),
('CHN103', 'Chennai', 'Chennai Central', 'Chennai Suburb 3'),
('CHN104', 'Chennai', 'Chennai Central', 'Chennai Suburb 4'),
('CHN105', 'Chennai', 'Chennai Central', 'Chennai Suburb 5'),
('CHN106', 'Chennai', 'Chennai Central', 'Chennai Suburb 6'),
('CHN107', 'Chennai', 'Chennai Central', 'Chennai Suburb 7'),
('CHN108', 'Chennai', 'Chennai Central', 'Chennai Suburb 8'),
('CHN109', 'Chennai', 'Chennai Central', 'Chennai Suburb 9'),
('CHN110', 'Chennai', 'Chennai Central', 'Chennai Suburb 10'),
('CBE101', 'Coimbatore', 'Coimbatore Central', 'Coimbatore Suburb 1'),
('CBE102', 'Coimbatore', 'Coimbatore Central', 'Coimbatore Suburb 2'),
('CBE103', 'Coimbatore', 'Coimbatore Central', 'Coimbatore Suburb 3'),
('CBE104', 'Coimbatore', 'Coimbatore Central', 'Coimbatore Suburb 4'),
('CBE105', 'Coimbatore', 'Coimbatore Central', 'Coimbatore Suburb 5'),
('CBE106', 'Coimbatore', 'Coimbatore Central', 'Coimbatore Suburb 6'),
('CBE107', 'Coimbatore', 'Coimbatore Central', 'Coimbatore Suburb 7'),
('CBE108', 'Coimbatore', 'Coimbatore Central', 'Coimbatore Suburb 8'),
('CBE109', 'Coimbatore', 'Coimbatore Central', 'Coimbatore Suburb 9'),
('CBE110', 'Coimbatore', 'Coimbatore Central', 'Coimbatore Suburb 10'),
('CUD101', 'Cuddalore', 'Cuddalore Central', 'Cuddalore Suburb 1'),
('CUD102', 'Cuddalore', 'Cuddalore Central', 'Cuddalore Suburb 2'),
('CUD103', 'Cuddalore', 'Cuddalore Central', 'Cuddalore Suburb 3'),
('CUD104', 'Cuddalore', 'Cuddalore Central', 'Cuddalore Suburb 4'),
('CUD105', 'Cuddalore', 'Cuddalore Central', 'Cuddalore Suburb 5'),
('CUD106', 'Cuddalore', 'Cuddalore Central', 'Cuddalore Suburb 6'),
('CUD107', 'Cuddalore', 'Cuddalore Central', 'Cuddalore Suburb 7'),
('CUD108', 'Cuddalore', 'Cuddalore Central', 'Cuddalore Suburb 8'),
('CUD109', 'Cuddalore', 'Cuddalore Central', 'Cuddalore Suburb 9'),
('CUD110', 'Cuddalore', 'Cuddalore Central', 'Cuddalore Suburb 10'),
('DPI101', 'Dharmapuri', 'Dharmapuri Central', 'Dharmapuri Suburb 1'),
('DPI102', 'Dharmapuri', 'Dharmapuri Central', 'Dharmapuri Suburb 2'),
('DPI103', 'Dharmapuri', 'Dharmapuri Central', 'Dharmapuri Suburb 3'),
('DPI104', 'Dharmapuri', 'Dharmapuri Central', 'Dharmapuri Suburb 4'),
('DPI105', 'Dharmapuri', 'Dharmapuri Central', 'Dharmapuri Suburb 5'),
('DPI106', 'Dharmapuri', 'Dharmapuri Central', 'Dharmapuri Suburb 6'),
('DPI107', 'Dharmapuri', 'Dharmapuri Central', 'Dharmapuri Suburb 7'),
('DPI108', 'Dharmapuri', 'Dharmapuri Central', 'Dharmapuri Suburb 8'),
('DPI109', 'Dharmapuri', 'Dharmapuri Central', 'Dharmapuri Suburb 9'),
('DPI110', 'Dharmapuri', 'Dharmapuri Central', 'Dharmapuri Suburb 10'),
('DGL101', 'Dindigul', 'Dindigul Central', 'Dindigul Suburb 1'),
('DGL102', 'Dindigul', 'Dindigul Central', 'Dindigul Suburb 2'),
('DGL103', 'Dindigul', 'Dindigul Central', 'Dindigul Suburb 3'),
('DGL104', 'Dindigul', 'Dindigul Central', 'Dindigul Suburb 4'),
('DGL105', 'Dindigul', 'Dindigul Central', 'Dindigul Suburb 5'),
('DGL106', 'Dindigul', 'Dindigul Central', 'Dindigul Suburb 6'),
('DGL107', 'Dindigul', 'Dindigul Central', 'Dindigul Suburb 7'),
('DGL108', 'Dindigul', 'Dindigul Central', 'Dindigul Suburb 8'),
('DGL109', 'Dindigul', 'Dindigul Central', 'Dindigul Suburb 9'),
('DGL110', 'Dindigul', 'Dindigul Central', 'Dindigul Suburb 10'),
('ERD101', 'Erode', 'Erode Central', 'Erode Suburb 1'),
('ERD102', 'Erode', 'Erode Central', 'Erode Suburb 2'),
('ERD103', 'Erode', 'Erode Central', 'Erode Suburb 3'),
('ERD104', 'Erode', 'Erode Central', 'Erode Suburb 4'),
('ERD105', 'Erode', 'Erode Central', 'Erode Suburb 5'),
('ERD106', 'Erode', 'Erode Central', 'Erode Suburb 6'),
('ERD107', 'Erode', 'Erode Central', 'Erode Suburb 7'),
('ERD108', 'Erode', 'Erode Central', 'Erode Suburb 8'),
('ERD109', 'Erode', 'Erode Central', 'Erode Suburb 9'),
('ERD110', 'Erode', 'Erode Central', 'Erode Suburb 10'),
('KCH101', 'Kallakurichi', 'Kallakurichi Central', 'Kallakurichi Suburb 1'),
('KCH102', 'Kallakurichi', 'Kallakurichi Central', 'Kallakurichi Suburb 2'),
('KCH103', 'Kallakurichi', 'Kallakurichi Central', 'Kallakurichi Suburb 3'),
('KCH104', 'Kallakurichi', 'Kallakurichi Central', 'Kallakurichi Suburb 4'),
('KCH105', 'Kallakurichi', 'Kallakurichi Central', 'Kallakurichi Suburb 5'),
('KCH106', 'Kallakurichi', 'Kallakurichi Central', 'Kallakurichi Suburb 6'),
('KCH107', 'Kallakurichi', 'Kallakurichi Central', 'Kallakurichi Suburb 7'),
('KCH108', 'Kallakurichi', 'Kallakurichi Central', 'Kallakurichi Suburb 8'),
('KCH109', 'Kallakurichi', 'Kallakurichi Central', 'Kallakurichi Suburb 9'),
('KCH110', 'Kallakurichi', 'Kallakurichi Central', 'Kallakurichi Suburb 10'),
('KPM101', 'Kanchipuram', 'Kanchipuram Central', 'Kanchipuram Suburb 1'),
('KPM102', 'Kanchipuram', 'Kanchipuram Central', 'Kanchipuram Suburb 2'),
('KPM103', 'Kanchipuram', 'Kanchipuram Central', 'Kanchipuram Suburb 3'),
('KPM104', 'Kanchipuram', 'Kanchipuram Central', 'Kanchipuram Suburb 4'),
('KPM105', 'Kanchipuram', 'Kanchipuram Central', 'Kanchipuram Suburb 5'),
('KPM106', 'Kanchipuram', 'Kanchipuram Central', 'Kanchipuram Suburb 6'),
('KPM107', 'Kanchipuram', 'Kanchipuram Central', 'Kanchipuram Suburb 7'),
('KPM108', 'Kanchipuram', 'Kanchipuram Central', 'Kanchipuram Suburb 8'),
('KPM109', 'Kanchipuram', 'Kanchipuram Central', 'Kanchipuram Suburb 9'),
('KPM110', 'Kanchipuram', 'Kanchipuram Central', 'Kanchipuram Suburb 10'),
('KKY101', 'Kanyakumari', 'Kanyakumari Central', 'Kanyakumari Suburb 1'),
('KKY102', 'Kanyakumari', 'Kanyakumari Central', 'Kanyakumari Suburb 2'),
('KKY103', 'Kanyakumari', 'Kanyakumari Central', 'Kanyakumari Suburb 3'),
('KKY104', 'Kanyakumari', 'Kanyakumari Central', 'Kanyakumari Suburb 4'),
('KKY105', 'Kanyakumari', 'Kanyakumari Central', 'Kanyakumari Suburb 5'),
('KKY106', 'Kanyakumari', 'Kanyakumari Central', 'Kanyakumari Suburb 6'),
('KKY107', 'Kanyakumari', 'Kanyakumari Central', 'Kanyakumari Suburb 7'),
('KKY108', 'Kanyakumari', 'Kanyakumari Central', 'Kanyakumari Suburb 8'),
('KKY109', 'Kanyakumari', 'Kanyakumari Central', 'Kanyakumari Suburb 9'),
('KKY110', 'Kanyakumari', 'Kanyakumari Central', 'Kanyakumari Suburb 10'),
('KRR101', 'Karur', 'Karur Central', 'Karur Suburb 1'),
('KRR102', 'Karur', 'Karur Central', 'Karur Suburb 2'),
('KRR103', 'Karur', 'Karur Central', 'Karur Suburb 3'),
('KRR104', 'Karur', 'Karur Central', 'Karur Suburb 4'),
('KRR105', 'Karur', 'Karur Central', 'Karur Suburb 5'),
('KRR106', 'Karur', 'Karur Central', 'Karur Suburb 6'),
('KRR107', 'Karur', 'Karur Central', 'Karur Suburb 7'),
('KRR108', 'Karur', 'Karur Central', 'Karur Suburb 8'),
('KRR109', 'Karur', 'Karur Central', 'Karur Suburb 9'),
('KRR110', 'Karur', 'Karur Central', 'Karur Suburb 10'),
('KGI101', 'Krishnagiri', 'Krishnagiri Central', 'Krishnagiri Suburb 1'),
('KGI102', 'Krishnagiri', 'Krishnagiri Central', 'Krishnagiri Suburb 2'),
('KGI103', 'Krishnagiri', 'Krishnagiri Central', 'Krishnagiri Suburb 3'),
('KGI104', 'Krishnagiri', 'Krishnagiri Central', 'Krishnagiri Suburb 4'),
('KGI105', 'Krishnagiri', 'Krishnagiri Central', 'Krishnagiri Suburb 5'),
('KGI106', 'Krishnagiri', 'Krishnagiri Central', 'Krishnagiri Suburb 6'),
('KGI107', 'Krishnagiri', 'Krishnagiri Central', 'Krishnagiri Suburb 7'),
('KGI108', 'Krishnagiri', 'Krishnagiri Central', 'Krishnagiri Suburb 8'),
('KGI109', 'Krishnagiri', 'Krishnagiri Central', 'Krishnagiri Suburb 9'),
('KGI110', 'Krishnagiri', 'Krishnagiri Central', 'Krishnagiri Suburb 10'),
('MDU101', 'Madurai', 'Madurai Central', 'Madurai Suburb 1'),
('MDU102', 'Madurai', 'Madurai Central', 'Madurai Suburb 2'),
('MDU103', 'Madurai', 'Madurai Central', 'Madurai Suburb 3'),
('MDU104', 'Madurai', 'Madurai Central', 'Madurai Suburb 4'),
('MDU105', 'Madurai', 'Madurai Central', 'Madurai Suburb 5'),
('MDU106', 'Madurai', 'Madurai Central', 'Madurai Suburb 6'),
('MDU107', 'Madurai', 'Madurai Central', 'Madurai Suburb 7'),
('MDU108', 'Madurai', 'Madurai Central', 'Madurai Suburb 8'),
('MDU109', 'Madurai', 'Madurai Central', 'Madurai Suburb 9'),
('MDU110', 'Madurai', 'Madurai Central', 'Madurai Suburb 10'),
('MYD101', 'Mayiladuthurai', 'Mayiladuthurai Central', 'Mayiladuthurai Suburb 1'),
('MYD102', 'Mayiladuthurai', 'Mayiladuthurai Central', 'Mayiladuthurai Suburb 2'),
('MYD103', 'Mayiladuthurai', 'Mayiladuthurai Central', 'Mayiladuthurai Suburb 3'),
('MYD104', 'Mayiladuthurai', 'Mayiladuthurai Central', 'Mayiladuthurai Suburb 4'),
('MYD105', 'Mayiladuthurai', 'Mayiladuthurai Central', 'Mayiladuthurai Suburb 5'),
('MYD106', 'Mayiladuthurai', 'Mayiladuthurai Central', 'Mayiladuthurai Suburb 6'),
('MYD107', 'Mayiladuthurai', 'Mayiladuthurai Central', 'Mayiladuthurai Suburb 7'),
('MYD108', 'Mayiladuthurai', 'Mayiladuthurai Central', 'Mayiladuthurai Suburb 8'),
('MYD109', 'Mayiladuthurai', 'Mayiladuthurai Central', 'Mayiladuthurai Suburb 9'),
('MYD110', 'Mayiladuthurai', 'Mayiladuthurai Central', 'Mayiladuthurai Suburb 10'),
('NGT101', 'Nagapattinam', 'Nagapattinam Central', 'Nagapattinam Suburb 1'),
('NGT102', 'Nagapattinam', 'Nagapattinam Central', 'Nagapattinam Suburb 2'),
('NGT103', 'Nagapattinam', 'Nagapattinam Central', 'Nagapattinam Suburb 3'),
('NGT104', 'Nagapattinam', 'Nagapattinam Central', 'Nagapattinam Suburb 4'),
('NGT105', 'Nagapattinam', 'Nagapattinam Central', 'Nagapattinam Suburb 5'),
('NGT106', 'Nagapattinam', 'Nagapattinam Central', 'Nagapattinam Suburb 6'),
('NGT107', 'Nagapattinam', 'Nagapattinam Central', 'Nagapattinam Suburb 7'),
('NGT108', 'Nagapattinam', 'Nagapattinam Central', 'Nagapattinam Suburb 8'),
('NGT109', 'Nagapattinam', 'Nagapattinam Central', 'Nagapattinam Suburb 9'),
('NGT110', 'Nagapattinam', 'Nagapattinam Central', 'Nagapattinam Suburb 10'),
('NMK101', 'Namakkal', 'Namakkal Central', 'Namakkal Suburb 1'),
('NMK102', 'Namakkal', 'Namakkal Central', 'Namakkal Suburb 2'),
('NMK103', 'Namakkal', 'Namakkal Central', 'Namakkal Suburb 3'),
('NMK104', 'Namakkal', 'Namakkal Central', 'Namakkal Suburb 4'),
('NMK105', 'Namakkal', 'Namakkal Central', 'Namakkal Suburb 5'),
('NMK106', 'Namakkal', 'Namakkal Central', 'Namakkal Suburb 6'),
('NMK107', 'Namakkal', 'Namakkal Central', 'Namakkal Suburb 7'),
('NMK108', 'Namakkal', 'Namakkal Central', 'Namakkal Suburb 8'),
('NMK109', 'Namakkal', 'Namakkal Central', 'Namakkal Suburb 9'),
('NMK110', 'Namakkal', 'Namakkal Central', 'Namakkal Suburb 10'),
('NIL101', 'Nilgiris', 'Nilgiris Central', 'Nilgiris Suburb 1'),
('NIL102', 'Nilgiris', 'Nilgiris Central', 'Nilgiris Suburb 2'),
('NIL103', 'Nilgiris', 'Nilgiris Central', 'Nilgiris Suburb 3'),
('NIL104', 'Nilgiris', 'Nilgiris Central', 'Nilgiris Suburb 4'),
('NIL105', 'Nilgiris', 'Nilgiris Central', 'Nilgiris Suburb 5'),
('NIL106', 'Nilgiris', 'Nilgiris Central', 'Nilgiris Suburb 6'),
('NIL107', 'Nilgiris', 'Nilgiris Central', 'Nilgiris Suburb 7'),
('NIL108', 'Nilgiris', 'Nilgiris Central', 'Nilgiris Suburb 8'),
('NIL109', 'Nilgiris', 'Nilgiris Central', 'Nilgiris Suburb 9'),
('NIL110', 'Nilgiris', 'Nilgiris Central', 'Nilgiris Suburb 10'),
('PRB101', 'Perambalur', 'Perambalur Central', 'Perambalur Suburb 1'),
('PRB102', 'Perambalur', 'Perambalur Central', 'Perambalur Suburb 2'),
('PRB103', 'Perambalur', 'Perambalur Central', 'Perambalur Suburb 3'),
('PRB104', 'Perambalur', 'Perambalur Central', 'Perambalur Suburb 4'),
('PRB105', 'Perambalur', 'Perambalur Central', 'Perambalur Suburb 5'),
('PRB106', 'Perambalur', 'Perambalur Central', 'Perambalur Suburb 6'),
('PRB107', 'Perambalur', 'Perambalur Central', 'Perambalur Suburb 7'),
('PRB108', 'Perambalur', 'Perambalur Central', 'Perambalur Suburb 8'),
('PRB109', 'Perambalur', 'Perambalur Central', 'Perambalur Suburb 9'),
('PRB110', 'Perambalur', 'Perambalur Central', 'Perambalur Suburb 10'),
('PDK101', 'Pudukkottai', 'Pudukkottai Central', 'Pudukkottai Suburb 1'),
('PDK102', 'Pudukkottai', 'Pudukkottai Central', 'Pudukkottai Suburb 2'),
('PDK103', 'Pudukkottai', 'Pudukkottai Central', 'Pudukkottai Suburb 3'),
('PDK104', 'Pudukkottai', 'Pudukkottai Central', 'Pudukkottai Suburb 4'),
('PDK105', 'Pudukkottai', 'Pudukkottai Central', 'Pudukkottai Suburb 5'),
('PDK106', 'Pudukkottai', 'Pudukkottai Central', 'Pudukkottai Suburb 6'),
('PDK107', 'Pudukkottai', 'Pudukkottai Central', 'Pudukkottai Suburb 7'),
('PDK108', 'Pudukkottai', 'Pudukkottai Central', 'Pudukkottai Suburb 8'),
('PDK109', 'Pudukkottai', 'Pudukkottai Central', 'Pudukkottai Suburb 9'),
('PDK110', 'Pudukkottai', 'Pudukkottai Central', 'Pudukkottai Suburb 10'),
('RMD101', 'Ramanathapuram', 'Ramanathapuram Central', 'Ramanathapuram Suburb 1'),
('RMD102', 'Ramanathapuram', 'Ramanathapuram Central', 'Ramanathapuram Suburb 2'),
('RMD103', 'Ramanathapuram', 'Ramanathapuram Central', 'Ramanathapuram Suburb 3'),
('RMD104', 'Ramanathapuram', 'Ramanathapuram Central', 'Ramanathapuram Suburb 4'),
('RMD105', 'Ramanathapuram', 'Ramanathapuram Central', 'Ramanathapuram Suburb 5'),
('RMD106', 'Ramanathapuram', 'Ramanathapuram Central', 'Ramanathapuram Suburb 6'),
('RMD107', 'Ramanathapuram', 'Ramanathapuram Central', 'Ramanathapuram Suburb 7'),
('RMD108', 'Ramanathapuram', 'Ramanathapuram Central', 'Ramanathapuram Suburb 8'),
('RMD109', 'Ramanathapuram', 'Ramanathapuram Central', 'Ramanathapuram Suburb 9'),
('RMD110', 'Ramanathapuram', 'Ramanathapuram Central', 'Ramanathapuram Suburb 10'),
('RNP101', 'Ranipet', 'Ranipet Central', 'Ranipet Suburb 1'),
('RNP102', 'Ranipet', 'Ranipet Central', 'Ranipet Suburb 2'),
('RNP103', 'Ranipet', 'Ranipet Central', 'Ranipet Suburb 3'),
('RNP104', 'Ranipet', 'Ranipet Central', 'Ranipet Suburb 4'),
('RNP105', 'Ranipet', 'Ranipet Central', 'Ranipet Suburb 5'),
('RNP106', 'Ranipet', 'Ranipet Central', 'Ranipet Suburb 6'),
('RNP107', 'Ranipet', 'Ranipet Central', 'Ranipet Suburb 7'),
('RNP108', 'Ranipet', 'Ranipet Central', 'Ranipet Suburb 8'),
('RNP109', 'Ranipet', 'Ranipet Central', 'Ranipet Suburb 9'),
('RNP110', 'Ranipet', 'Ranipet Central', 'Ranipet Suburb 10'),
('SLM101', 'Salem', 'Salem Central', 'Salem Suburb 1'),
('SLM102', 'Salem', 'Salem Central', 'Salem Suburb 2'),
('SLM103', 'Salem', 'Salem Central', 'Salem Suburb 3'),
('SLM104', 'Salem', 'Salem Central', 'Salem Suburb 4'),
('SLM105', 'Salem', 'Salem Central', 'Salem Suburb 5'),
('SLM106', 'Salem', 'Salem Central', 'Salem Suburb 6'),
('SLM107', 'Salem', 'Salem Central', 'Salem Suburb 7'),
('SLM108', 'Salem', 'Salem Central', 'Salem Suburb 8'),
('SLM109', 'Salem', 'Salem Central', 'Salem Suburb 9'),
('SLM110', 'Salem', 'Salem Central', 'Salem Suburb 10'),
('SVG101', 'Sivaganga', 'Sivaganga Central', 'Sivaganga Suburb 1'),
('SVG102', 'Sivaganga', 'Sivaganga Central', 'Sivaganga Suburb 2'),
('SVG103', 'Sivaganga', 'Sivaganga Central', 'Sivaganga Suburb 3'),
('SVG104', 'Sivaganga', 'Sivaganga Central', 'Sivaganga Suburb 4'),
('SVG105', 'Sivaganga', 'Sivaganga Central', 'Sivaganga Suburb 5'),
('SVG106', 'Sivaganga', 'Sivaganga Central', 'Sivaganga Suburb 6'),
('SVG107', 'Sivaganga', 'Sivaganga Central', 'Sivaganga Suburb 7'),
('SVG108', 'Sivaganga', 'Sivaganga Central', 'Sivaganga Suburb 8'),
('SVG109', 'Sivaganga', 'Sivaganga Central', 'Sivaganga Suburb 9'),
('SVG110', 'Sivaganga', 'Sivaganga Central', 'Sivaganga Suburb 10'),
('TKS101', 'Tenkasi', 'Tenkasi Central', 'Tenkasi Suburb 1'),
('TKS102', 'Tenkasi', 'Tenkasi Central', 'Tenkasi Suburb 2'),
('TKS103', 'Tenkasi', 'Tenkasi Central', 'Tenkasi Suburb 3'),
('TKS104', 'Tenkasi', 'Tenkasi Central', 'Tenkasi Suburb 4'),
('TKS105', 'Tenkasi', 'Tenkasi Central', 'Tenkasi Suburb 5'),
('TKS106', 'Tenkasi', 'Tenkasi Central', 'Tenkasi Suburb 6'),
('TKS107', 'Tenkasi', 'Tenkasi Central', 'Tenkasi Suburb 7'),
('TKS108', 'Tenkasi', 'Tenkasi Central', 'Tenkasi Suburb 8'),
('TKS109', 'Tenkasi', 'Tenkasi Central', 'Tenkasi Suburb 9'),
('TKS110', 'Tenkasi', 'Tenkasi Central', 'Tenkasi Suburb 10'),
('TJV101', 'Thanjavur', 'Thanjavur Central', 'Thanjavur Suburb 1'),
('TJV102', 'Thanjavur', 'Thanjavur Central', 'Thanjavur Suburb 2'),
('TJV103', 'Thanjavur', 'Thanjavur Central', 'Thanjavur Suburb 3'),
('TJV104', 'Thanjavur', 'Thanjavur Central', 'Thanjavur Suburb 4'),
('TJV105', 'Thanjavur', 'Thanjavur Central', 'Thanjavur Suburb 5'),
('TJV106', 'Thanjavur', 'Thanjavur Central', 'Thanjavur Suburb 6'),
('TJV107', 'Thanjavur', 'Thanjavur Central', 'Thanjavur Suburb 7'),
('TJV108', 'Thanjavur', 'Thanjavur Central', 'Thanjavur Suburb 8'),
('TJV109', 'Thanjavur', 'Thanjavur Central', 'Thanjavur Suburb 9'),
('TJV110', 'Thanjavur', 'Thanjavur Central', 'Thanjavur Suburb 10'),
('TNI101', 'Theni', 'Theni Central', 'Theni Suburb 1'),
('TNI102', 'Theni', 'Theni Central', 'Theni Suburb 2'),
('TNI103', 'Theni', 'Theni Central', 'Theni Suburb 3'),
('TNI104', 'Theni', 'Theni Central', 'Theni Suburb 4'),
('TNI105', 'Theni', 'Theni Central', 'Theni Suburb 5'),
('TNI106', 'Theni', 'Theni Central', 'Theni Suburb 6'),
('TNI107', 'Theni', 'Theni Central', 'Theni Suburb 7'),
('TNI108', 'Theni', 'Theni Central', 'Theni Suburb 8'),
('TNI109', 'Theni', 'Theni Central', 'Theni Suburb 9'),
('TNI110', 'Theni', 'Theni Central', 'Theni Suburb 10'),
('TLR101', 'Tiruvallur', 'Tiruvallur Central', 'Tiruvallur Suburb 1'),
('TLR102', 'Tiruvallur', 'Tiruvallur Central', 'Tiruvallur Suburb 2'),
('TLR103', 'Tiruvallur', 'Tiruvallur Central', 'Tiruvallur Suburb 3'),
('TLR104', 'Tiruvallur', 'Tiruvallur Central', 'Tiruvallur Suburb 4'),
('TLR105', 'Tiruvallur', 'Tiruvallur Central', 'Tiruvallur Suburb 5'),
('TLR106', 'Tiruvallur', 'Tiruvallur Central', 'Tiruvallur Suburb 6'),
('TLR107', 'Tiruvallur', 'Tiruvallur Central', 'Tiruvallur Suburb 7'),
('TLR108', 'Tiruvallur', 'Tiruvallur Central', 'Tiruvallur Suburb 8'),
('TLR109', 'Tiruvallur', 'Tiruvallur Central', 'Tiruvallur Suburb 9'),
('TLR110', 'Tiruvallur', 'Tiruvallur Central', 'Tiruvallur Suburb 10'),
('TVR101', 'Tiruvarur', 'Tiruvarur Central', 'Tiruvarur Suburb 1'),
('TVR102', 'Tiruvarur', 'Tiruvarur Central', 'Tiruvarur Suburb 2'),
('TVR103', 'Tiruvarur', 'Tiruvarur Central', 'Tiruvarur Suburb 3'),
('TVR104', 'Tiruvarur', 'Tiruvarur Central', 'Tiruvarur Suburb 4'),
('TVR105', 'Tiruvarur', 'Tiruvarur Central', 'Tiruvarur Suburb 5'),
('TVR106', 'Tiruvarur', 'Tiruvarur Central', 'Tiruvarur Suburb 6'),
('TVR107', 'Tiruvarur', 'Tiruvarur Central', 'Tiruvarur Suburb 7'),
('TVR108', 'Tiruvarur', 'Tiruvarur Central', 'Tiruvarur Suburb 8'),
('TVR109', 'Tiruvarur', 'Tiruvarur Central', 'Tiruvarur Suburb 9'),
('TVR110', 'Tiruvarur', 'Tiruvarur Central', 'Tiruvarur Suburb 10'),
('TUT101', 'Thoothukudi', 'Thoothukudi Central', 'Thoothukudi Suburb 1'),
('TUT102', 'Thoothukudi', 'Thoothukudi Central', 'Thoothukudi Suburb 2'),
('TUT103', 'Thoothukudi', 'Thoothukudi Central', 'Thoothukudi Suburb 3'),
('TUT104', 'Thoothukudi', 'Thoothukudi Central', 'Thoothukudi Suburb 4'),
('TUT105', 'Thoothukudi', 'Thoothukudi Central', 'Thoothukudi Suburb 5'),
('TUT106', 'Thoothukudi', 'Thoothukudi Central', 'Thoothukudi Suburb 6'),
('TUT107', 'Thoothukudi', 'Thoothukudi Central', 'Thoothukudi Suburb 7'),
('TUT108', 'Thoothukudi', 'Thoothukudi Central', 'Thoothukudi Suburb 8'),
('TUT109', 'Thoothukudi', 'Thoothukudi Central', 'Thoothukudi Suburb 9'),
('TUT110', 'Thoothukudi', 'Thoothukudi Central', 'Thoothukudi Suburb 10'),
('TRY101', 'Tiruchirappalli', 'Tiruchirappalli Central', 'Tiruchirappalli Suburb 1'),
('TRY102', 'Tiruchirappalli', 'Tiruchirappalli Central', 'Tiruchirappalli Suburb 2'),
('TRY103', 'Tiruchirappalli', 'Tiruchirappalli Central', 'Tiruchirappalli Suburb 3'),
('TRY104', 'Tiruchirappalli', 'Tiruchirappalli Central', 'Tiruchirappalli Suburb 4'),
('TRY105', 'Tiruchirappalli', 'Tiruchirappalli Central', 'Tiruchirappalli Suburb 5'),
('TRY106', 'Tiruchirappalli', 'Tiruchirappalli Central', 'Tiruchirappalli Suburb 6'),
('TRY107', 'Tiruchirappalli', 'Tiruchirappalli Central', 'Tiruchirappalli Suburb 7'),
('TRY108', 'Tiruchirappalli', 'Tiruchirappalli Central', 'Tiruchirappalli Suburb 8'),
('TRY109', 'Tiruchirappalli', 'Tiruchirappalli Central', 'Tiruchirappalli Suburb 9'),
('TRY110', 'Tiruchirappalli', 'Tiruchirappalli Central', 'Tiruchirappalli Suburb 10'),
('TNV101', 'Tirunelveli', 'Tirunelveli Central', 'Tirunelveli Suburb 1'),
('TNV102', 'Tirunelveli', 'Tirunelveli Central', 'Tirunelveli Suburb 2'),
('TNV103', 'Tirunelveli', 'Tirunelveli Central', 'Tirunelveli Suburb 3'),
('TNV104', 'Tirunelveli', 'Tirunelveli Central', 'Tirunelveli Suburb 4'),
('TNV105', 'Tirunelveli', 'Tirunelveli Central', 'Tirunelveli Suburb 5'),
('TNV106', 'Tirunelveli', 'Tirunelveli Central', 'Tirunelveli Suburb 6'),
('TNV107', 'Tirunelveli', 'Tirunelveli Central', 'Tirunelveli Suburb 7'),
('TNV108', 'Tirunelveli', 'Tirunelveli Central', 'Tirunelveli Suburb 8'),
('TNV109', 'Tirunelveli', 'Tirunelveli Central', 'Tirunelveli Suburb 9'),
('TNV110', 'Tirunelveli', 'Tirunelveli Central', 'Tirunelveli Suburb 10'),
('TPT101', 'Tirupathur', 'Tirupathur Central', 'Tirupathur Suburb 1'),
('TPT102', 'Tirupathur', 'Tirupathur Central', 'Tirupathur Suburb 2'),
('TPT103', 'Tirupathur', 'Tirupathur Central', 'Tirupathur Suburb 3'),
('TPT104', 'Tirupathur', 'Tirupathur Central', 'Tirupathur Suburb 4'),
('TPT105', 'Tirupathur', 'Tirupathur Central', 'Tirupathur Suburb 5'),
('TPT106', 'Tirupathur', 'Tirupathur Central', 'Tirupathur Suburb 6'),
('TPT107', 'Tirupathur', 'Tirupathur Central', 'Tirupathur Suburb 7'),
('TPT108', 'Tirupathur', 'Tirupathur Central', 'Tirupathur Suburb 8'),
('TPT109', 'Tirupathur', 'Tirupathur Central', 'Tirupathur Suburb 9'),
('TPT110', 'Tirupathur', 'Tirupathur Central', 'Tirupathur Suburb 10'),
('TUP101', 'Tiruppur', 'Tiruppur Central', 'Tiruppur Suburb 1'),
('TUP102', 'Tiruppur', 'Tiruppur Central', 'Tiruppur Suburb 2'),
('TUP103', 'Tiruppur', 'Tiruppur Central', 'Tiruppur Suburb 3'),
('TUP104', 'Tiruppur', 'Tiruppur Central', 'Tiruppur Suburb 4'),
('TUP105', 'Tiruppur', 'Tiruppur Central', 'Tiruppur Suburb 5'),
('TUP106', 'Tiruppur', 'Tiruppur Central', 'Tiruppur Suburb 6'),
('TUP107', 'Tiruppur', 'Tiruppur Central', 'Tiruppur Suburb 7'),
('TUP108', 'Tiruppur', 'Tiruppur Central', 'Tiruppur Suburb 8'),
('TUP109', 'Tiruppur', 'Tiruppur Central', 'Tiruppur Suburb 9'),
('TUP110', 'Tiruppur', 'Tiruppur Central', 'Tiruppur Suburb 10'),
('TVM101', 'Tiruvannamalai', 'Tiruvannamalai Central', 'Tiruvannamalai Suburb 1'),
('TVM102', 'Tiruvannamalai', 'Tiruvannamalai Central', 'Tiruvannamalai Suburb 2'),
('TVM103', 'Tiruvannamalai', 'Tiruvannamalai Central', 'Tiruvannamalai Suburb 3'),
('TVM104', 'Tiruvannamalai', 'Tiruvannamalai Central', 'Tiruvannamalai Suburb 4'),
('TVM105', 'Tiruvannamalai', 'Tiruvannamalai Central', 'Tiruvannamalai Suburb 5'),
('TVM106', 'Tiruvannamalai', 'Tiruvannamalai Central', 'Tiruvannamalai Suburb 6'),
('TVM107', 'Tiruvannamalai', 'Tiruvannamalai Central', 'Tiruvannamalai Suburb 7'),
('TVM108', 'Tiruvannamalai', 'Tiruvannamalai Central', 'Tiruvannamalai Suburb 8'),
('TVM109', 'Tiruvannamalai', 'Tiruvannamalai Central', 'Tiruvannamalai Suburb 9'),
('TVM110', 'Tiruvannamalai', 'Tiruvannamalai Central', 'Tiruvannamalai Suburb 10'),
('VEL101', 'Vellore', 'Vellore Central', 'Vellore Suburb 1'),
('VEL102', 'Vellore', 'Vellore Central', 'Vellore Suburb 2'),
('VEL103', 'Vellore', 'Vellore Central', 'Vellore Suburb 3'),
('VEL104', 'Vellore', 'Vellore Central', 'Vellore Suburb 4'),
('VEL105', 'Vellore', 'Vellore Central', 'Vellore Suburb 5'),
('VEL106', 'Vellore', 'Vellore Central', 'Vellore Suburb 6'),
('VEL107', 'Vellore', 'Vellore Central', 'Vellore Suburb 7'),
('VEL108', 'Vellore', 'Vellore Central', 'Vellore Suburb 8'),
('VEL109', 'Vellore', 'Vellore Central', 'Vellore Suburb 9'),
('VEL110', 'Vellore', 'Vellore Central', 'Vellore Suburb 10'),
('VPM101', 'Viluppuram', 'Viluppuram Central', 'Viluppuram Suburb 1'),
('VPM102', 'Viluppuram', 'Viluppuram Central', 'Viluppuram Suburb 2'),
('VPM103', 'Viluppuram', 'Viluppuram Central', 'Viluppuram Suburb 3'),
('VPM104', 'Viluppuram', 'Viluppuram Central', 'Viluppuram Suburb 4'),
('VPM105', 'Viluppuram', 'Viluppuram Central', 'Viluppuram Suburb 5'),
('VPM106', 'Viluppuram', 'Viluppuram Central', 'Viluppuram Suburb 6'),
('VPM107', 'Viluppuram', 'Viluppuram Central', 'Viluppuram Suburb 7'),
('VPM108', 'Viluppuram', 'Viluppuram Central', 'Viluppuram Suburb 8'),
('VPM109', 'Viluppuram', 'Viluppuram Central', 'Viluppuram Suburb 9'),
('VPM110', 'Viluppuram', 'Viluppuram Central', 'Viluppuram Suburb 10'),
('VNR101', 'Virudhunagar', 'Virudhunagar Central', 'Virudhunagar Suburb 1'),
('VNR102', 'Virudhunagar', 'Virudhunagar Central', 'Virudhunagar Suburb 2'),
('VNR103', 'Virudhunagar', 'Virudhunagar Central', 'Virudhunagar Suburb 3'),
('VNR104', 'Virudhunagar', 'Virudhunagar Central', 'Virudhunagar Suburb 4'),
('VNR105', 'Virudhunagar', 'Virudhunagar Central', 'Virudhunagar Suburb 5'),
('VNR106', 'Virudhunagar', 'Virudhunagar Central', 'Virudhunagar Suburb 6'),
('VNR107', 'Virudhunagar', 'Virudhunagar Central', 'Virudhunagar Suburb 7'),
('VNR108', 'Virudhunagar', 'Virudhunagar Central', 'Virudhunagar Suburb 8'),
('VNR109', 'Virudhunagar', 'Virudhunagar Central', 'Virudhunagar Suburb 9'),
('VNR110', 'Virudhunagar', 'Virudhunagar Central', 'Virudhunagar Suburb 10');

-- Sample Bus Stops for Madurai
INSERT IGNORE INTO bus_stops (name, city) VALUES 
('Melur', 'Madurai'), ('Thirumangalam', 'Madurai'), ('Usilampatti', 'Madurai'), ('Thiruparankundram', 'Madurai'), ('Vadipatti', 'Madurai'), ('Peraiyur', 'Madurai'), ('Sholavandan', 'Madurai'), ('Alanganallur', 'Madurai'), ('Palamedu', 'Madurai'), ('Paravai', 'Madurai'), ('T. Kallupatti', 'Madurai'), ('A. Vellalapatti', 'Madurai'), ('Elumalai', 'Madurai'), ('Harveypatti', 'Madurai'), ('Anaiyur', 'Madurai'), ('Avaniapuram', 'Madurai'), ('Anna Nagar', 'Madurai'), ('K.K. Nagar', 'Madurai'), ('Tallakulam', 'Madurai'), ('Goripalayam', 'Madurai'), ('Bibikulam', 'Madurai'), ('K. Pudur', 'Madurai'), ('S.S. Colony', 'Madurai'), ('Arappalayam', 'Madurai'), ('Simmakkal', 'Madurai'), ('Sellur', 'Madurai'), ('Palangantham', 'Madurai'), ('Pasumalai', 'Madurai'), ('Iyer Bungalow', 'Madurai'), ('Narimedu', 'Madurai'), ('Chokkikulam', 'Madurai'), ('Jaihindpuram', 'Madurai'), ('Ellis Nagar', 'Madurai'), ('Bethaniyapuram', 'Madurai'), ('Villapuram', 'Madurai'), ('Kochadai', 'Madurai'), ('Uthangudi', 'Madurai'), ('Munichalai', 'Madurai'), ('Othakadai', 'Madurai'), ('Karuppayurani', 'Madurai'), ('Samayanallur', 'Madurai'), ('Thanakkankulam', 'Madurai'), ('Vandiyur', 'Madurai'), ('Silaiman', 'Madurai'), ('Nagavakulam', 'Madurai'), ('Kalligudi', 'Madurai'), ('Samanatham', 'Madurai'), ('Arumbanur', 'Madurai'), ('Nagamalaipudukottai', 'Madurai'), ('Thiruppalai', 'Madurai');

-- Main District Center Stops (All 38 Districts)
INSERT IGNORE INTO bus_stops (name, city) VALUES 
('Ariyalur', 'Ariyalur'), ('Chengalpattu', 'Chengalpattu'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Cuddalore', 'Cuddalore'), ('Dharmapuri', 'Dharmapuri'), ('Dindigul', 'Dindigul'), ('Erode', 'Erode'), ('Kallakurichi', 'Kallakurichi'), ('Kancheepuram', 'Kancheepuram'), ('Kanyakumari', 'Kanyakumari'), ('Karur', 'Karur'), ('Krishnagiri', 'Krishnagiri'), ('Madurai', 'Madurai'), ('Mayiladuthurai', 'Mayiladuthurai'), ('Nagapattinam', 'Nagapattinam'), ('Namakkal', 'Namakkal'), ('Nilgiris', 'Nilgiris'), ('Perambalur', 'Perambalur'), ('Pudukkottai', 'Pudukkottai'), ('Ramanathapuram', 'Ramanathapuram'), ('Ranipet', 'Ranipet'), ('Salem', 'Salem'), ('Sivagangai', 'Sivagangai'), ('Tenkasi', 'Tenkasi'), ('Thanjavur', 'Thanjavur'), ('Theni', 'Theni'), ('Thiruvallur', 'Thiruvallur'), ('Thiruvarur', 'Thiruvarur'), ('Thoothukudi', 'Thoothukudi'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Tirunelveli', 'Tirunelveli'), ('Tirupathur', 'Tirupathur'), ('Tiruppur', 'Tiruppur'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Vellore', 'Vellore'), ('Viluppuram', 'Viluppuram'), ('Virudhunagar', 'Virudhunagar');

-- Initial Notification
INSERT IGNORE INTO notifications (message) VALUES ('Welcome to the Smart Bus Portal! Modernizing Urban Transit.');